- name: Build and push Docker images
  uses: docker/build-push-action@v1.1.0
  with:
    username: ${{ secrets.DOCKER_USERNAME }}
    password: ${{ secrets.DOCKER_PASSWORD }}
    repository: omrihaber/alakazam
    tag_with_ref: true
    tag_with_sha: true
