on:
  push:
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - uses: docker/build-push-action@v1.1.0
        name: Build and push Docker images
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: omrihaber/alakazam
          tag_with_ref: true
          tag_with_sha: true
